---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://YOUR_GITHUB_USERNAME.github.io/trmnl-max-payne-quotes-plugin/quotes.json
polling_headers: ''
polling_body: ''
custom_fields:
- keyname: max_payne_quotes
  field_type: author_bio
  name: Max Payne Quotes
  description: Dark, noir quotes from the Max Payne trilogy. Experience the pain and philosophy of New York's most troubled detective. "The past is a gaping hole..."
  category: entertainment
  github_url: https://github.com/YOUR_GITHUB_USERNAME/trmnl-max-payne-quotes-plugin
  email_address: YOUR_EMAIL@example.com
name: Max Payne Quotes
refresh_interval: 1440
